name: Build

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # every weekday
    - cron: '0 0 * * 1-5'
    # every sunday (no-cache)
    - cron: '0 0 * * 0'
  workflow_dispatch:
    inputs:
      no-cache:
        description: 'Skip Docker cache'
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        golang:
          - "1.12"
          - "1.13"
          - "1.16"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.golang }}
          pull: ${{ github.event_name != 'pull_request' }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: articulate/articulate-golang:${{ matrix.golang }}
          platforms: linux/amd64,linux/arm64/v8
          cache-from: type=registry,ref=articulate/articulate-golang:${{ matrix.golang }}
          cache-to: type=inline
          no-cache: ${{ github.event.schedule == '0 0 * * 0' || (github.event_name == 'workflow_dispatch' && inputs.no-cache) }}
