name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        golang:
          - "1.12"
          - "1.13"
          - "1.16"
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.golang }}
          push: true
          tags: articulate/articulate-golang:${{ matrix.golang }}
          platforms: linux/amd64,linux/arm64/v8
          cache-from: type=registry,ref=articulate/articulate-golang:${{ matrix.golang }}
          cache-to: type=inline
