name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - "1.12"
          - "1.13"
          - "1.16"
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@0a6d062e780d218ea909a18365e0ab2e36d09612 # pin@v2.0.0
        with:
          dockerfile: ${{ matrix.image }}/Dockerfile
          ignore: DL3008
