name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - "1.12"
          - "1.13"
          - "1.16"
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@4b5806eb9c6bee4954fc0e0cc3ad6175fc9782c1 # pin@v3.0.0
        with:
          dockerfile: ${{ matrix.image }}/Dockerfile
          ignore: DL3008
