name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - "1.12"
          - "1.13"
          - "1.16"
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183 # pin@v2.1.0
        with:
          dockerfile: ${{ matrix.image }}/Dockerfile
